writings_dir: "src/writings"
naox_projects_file: "src/proj/naox_projects.yaml"
waozi_projects_file: "src/proj/projects.yaml"
templates_dir: "src/templates"
static_dir: "src/static"
assets_dir: "src/assets"
dist_dir: "dist"
writing_template: "writing.html"
writings_index_template: "writings_index.html"
projects_index_template: "projects_index.html"
max_writings: 2
max_projects_display: 2
index_file: "src/index.html"
site_title: "Waozi - Digital Tao"
site_url: "https://waozi.xyz"
author_name: "Martin Schiller"
site_description: "Explore Waozi, a digital reflection of consciousness. Discover tools for collective growth, crypto experiments, and philosophical musings"
