content_dir: "src/content"
writings_dir: "src/content/writings"
naox_projects_file: "src/content/data/naox_projects.yaml"
waozi_projects_file: "src/content/data/projects.yaml"
templates_dir: "src/templates"
static_dir: "src/static"
dist_dir: "dist"
main_template: "main.html"
writing_template: "writing.html"
writings_index_template: "writings_index.html"
projects_index_template: "projects_index.html"
max_writings: 2
max_projects_display: 2
index_file: "src/index.html"