name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Lua and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y lua5.3 liblua5.3-dev luarocks
        luarocks install --local luafilesystem
        luarocks install --local lyaml

    - name: Set Lua and LuaRocks paths
      run: |
        echo "export PATH=$HOME/.luarocks/bin:$PATH" >> $GITHUB_ENV
        echo "export LUA_PATH='$PWD/src/lua/?.lua;$HOME/.luarocks/share/lua/5.3/?.lua;$HOME/.luarocks/share/lua/5.3/?/init.lua;;'" >> $GITHUB_ENV
        echo "export LUA_CPATH='$HOME/.luarocks/lib/lua/5.3/?.so;;'" >> $GITHUB_ENV

    - name: Build the site
      run: lua src/lua/build.lua

    - name: Install Netlify CLI
      run: npm install -g netlify-cli

    - name: Deploy to Netlify
      run: netlify deploy --dir=dist --prod
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
